spring:
  application:
    name: token-service
  datasource:
    url: jdbc:mysql://103.120.177.83:3306/nandhu_test_db?useSSL=false
    username: root
    password: '!LDqqH3c_kKyqg7G'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
server:
  port: 7575
#  servlet:
#    context-path: /TOKEN-SERVICE-WEB/ 
 
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/
#zuul:
#  prefix: /api
#  routes:
#    greeting-service:
#      path: /users/**
#      url: http://localhost:7171/
#      service-id: greeting-service
#      strip-prefix: true
zuul:
#  prefix: /api
  routes:
    greeting-service:
#      path: /greetings-api/**
#      serviceId: greeting-service
      url: http://localhost:7171
#    serviceB:
#      path: /tasks-api/**
#      serviceId: task-service

