server:
  port: 7171
#  servlet:
#    context-path: /GREETING-SERVICE-WEB/
spring:  
  application:
    name: greeting-service

eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/